version: '3.3'
services:
    gocryptfs:
        container_name: gocryptfs
        privileged: false
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        env_file:
            - .env        
        volumes:
            - '/mnt/gocrypt:/encrypted'
            - '/opt/gocrypt:/decrypted:shared'
        image: vmirage/gocryptfs

