---
version: "3.4"
services:
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "${DOCKERHOME}/volumes/komga/config:/config"
      - /etc/timezone:/etc/timezone
      
      - /mnt/media/manga:/books
      - /opt/gocrypt/media/manga:/books/smanga
    user: "1000:1000"
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=Host(`m.${REVERSE_HOST}`)"
      - "traefik.http.routers.komga.entrypoints=web-secure"
      - "traefik.http.routers.komga.tls=true"
    networks: 
      - reverse
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/claim || exit 1
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 10s

networks:
  reverse:
    external:
      name: reverse
